## static_territories
UPDATE static_territories SET tr_name_uk='Африка' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_uk='Океанія' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_uk='Північна і Південна Америка' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_uk='Азія' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_uk='Європа' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_uk='Східна Азія' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_uk='Південно-східна Азія' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_uk='Центральна Азія' WHERE tr_iso_nr='143';
UPDATE static_territories SET tr_name_uk='Західна Азія' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_uk='Південна Європа' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_uk='Східна Європа' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_uk='Північна Європа' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_uk='Західна Європа' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_uk='Південна Америка' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_uk='Центральна Америка' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_uk='Північна Америка' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_uk='Карибський басейн' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_uk='Західна Африка' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_uk='Східна Африка' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_uk='Північна Африка' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_uk='Центральна Африка' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_uk='Південна частина Африки' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_uk='Австралія і Нова Зеландія' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_uk='Меланезія' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_uk='Мікронезія' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_uk='Полінезія' WHERE tr_iso_nr='61';
UPDATE static_territories SET tr_name_uk='Південна Азія' WHERE tr_iso_nr='34';


## static_countries
UPDATE static_countries SET cn_short_uk='Андорра' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_uk='Об\'єднані Арабські Емірати' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_uk='Афганістан' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_uk='Антігуа і Барбуда' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_uk='Ангилья' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_uk='Албанія' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_uk='Вірменія' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_uk='Нідерландські Антіли' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_uk='Ангола' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_uk='Антарктида' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_uk='Аргентина' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_uk='Американське Самоа' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_uk='Австрія' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_uk='Австралія' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_uk='Аруба' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_uk='Азербайджан' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_uk='Боснія і Герцеговина' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_uk='Барбадос' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_uk='Бангладеш' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_uk='Бельгія' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_uk='Буркина-Фасо' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_uk='Болгарія' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_uk='Бахрейн' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_uk='Бурунді' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_uk='Бенін' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_uk='Бермуди' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_uk='Бруней-даруссалам' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_uk='Болівія' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_uk='Бразилія' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_uk='Багами' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_uk='Бутан' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_uk='Острів Буве' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_uk='Ботсвана' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_uk='Білорусь' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_uk='Беліз' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_uk='Канада' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_uk='Кокосові (Килінг) острови' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_uk='Конго' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_uk='Центрально-африканська Республіка' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_uk='Конго' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_uk='Швейцарія' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_uk='Кот д\'Івуар' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_uk='Острови Кука' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_uk='Чілі' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_uk='Камерун' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_uk='Китай' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_uk='Колумбія' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_uk='Коста-Ріка' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_uk='Сербія і Черногорія' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_uk='Куба' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_uk='Кабо-Верде' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_uk='Острів Різдва' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_uk='Кіпр' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_uk='Чеська Республіка' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_uk='Німеччина' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_uk='Джібуті' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_uk='Данія' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_uk='Доміника' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_uk='Домініканська Республіка' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_uk='Алжир' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_uk='Еквадор' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_uk='Естонія' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_uk='Єгипет' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_uk='Західна Сахара' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_uk='Еритрея' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_uk='Іспанія' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_uk='Ефіопія' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_uk='Фінляндія' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_uk='Фіджі' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_uk='Фолклендські острови' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_uk='Мікронезія, федеральні штати' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_uk='Фарерськіє острови' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_uk='Франція' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_uk='Габон' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_uk='Сполучене Королівство' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_uk='Гренада' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_uk='Грузія' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_uk='Французька Гвіана' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_uk='Гана' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_uk='Гібралтар' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_uk='Гренландія' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_uk='Гамбія' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_uk='Гвінея' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_uk='Гваделупа' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_uk='Екваторіальна Гвінея' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_uk='Південна джорджія і Південні Сандвічеви острови' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_uk='Греція' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_uk='Гватемала' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_uk='Гуам' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_uk='Гвінея-Бісау' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_uk='Гайана' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_uk='Гонконг' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_uk='Острів Херд і острови Макдональд' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_uk='Гондурас' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_uk='Хорватія' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_uk='Гаїті' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_uk='Венгрія' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_uk='Індонезія' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_uk='Ірландія' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_uk='Ізраїль' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_uk='Індія' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_uk='Британська територія в Індійському океані' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_uk='Ірак' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_uk='Іран' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_uk='Ісландія' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_uk='Італія' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_uk='Ямайка' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_uk='Йорданія' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_uk='Японія' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_uk='Кенія' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_uk='Киргизія' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_uk='Камбоджа' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_uk='Кирібаті' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_uk='Комори' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_uk='Сен-китс і Невіс' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_uk='Північна Корея' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_uk='Південна Корея' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_uk='Кувейт' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_uk='Острови Кайман' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_uk='Казахстан' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_uk='Лаос' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_uk='Ліван' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_uk='Сент-Люсия' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_uk='Ліхтенштейн' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_uk='Шрі-Ланка' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_uk='Ліберія' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_uk='Лесото' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_uk='Литва' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_uk='Люксембург' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_uk='Латвія' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_uk='Лівійська Арабська Джамахирія' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_uk='Марокко' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_uk='Монако' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_uk='Молдова, республіка' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_uk='Мадагаскар' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_uk='Маршаллови Острови' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_uk='Македонія' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_uk='Малі' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_uk='Мьянма' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_uk='Монголія' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_uk='Макао' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_uk='Північні Маріанськіє острови' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_uk='Мартіника' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_uk='Мавританія' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_uk='Монтсеррат' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_uk='Мальта' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_uk='Маврикій' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_uk='Мальдіви' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_uk='Малаві' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_uk='Мексика' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_uk='Малайзія' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_uk='Мозамбік' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_uk='Намібія' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_uk='Нова Каледонія' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_uk='Нігер' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_uk='Острів Норфолк' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_uk='Нігерія' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_uk='Нікарагуа' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_uk='Нідерланди' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_uk='Норвегія' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_uk='Непал' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_uk='Науру' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_uk='Ніуе' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_uk='Нова Зеландія' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_uk='Оман' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_uk='Панама' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_uk='Перу' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_uk='Французька Полінезія' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_uk='Папуа - Нова Гвінея' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_uk='Філіппіни' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_uk='Пакістан' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_uk='Польща' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_uk='Сент-п\'єр і Мікелон' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_uk='Піткерн' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_uk='Пуерто-Ріко' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_uk='Палестинська територія' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_uk='Португалія' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_uk='Палау' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_uk='Парагвай' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_uk='Катар' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_uk='Реюньон' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_uk='Руминія' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_uk='Росія' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_uk='Руанда' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_uk='Саудовская Аравія' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_uk='Соломонови Острови' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_uk='Сейшели' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_uk='Судан' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_uk='Швеція' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_uk='Сінгапур' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_uk='Свята Олена' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_uk='Словенія' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_uk='Шпіцберген і Ян Майен' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_uk='Словакія' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_uk='Сьєрра-Леоне' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_uk='Сан-Маріно' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_uk='Сенегал' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_uk='Сомалі' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_uk='Сурінам' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_uk='Сан-Томе і Принсипи' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_uk='Сальвадор' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_uk='Сірійська Арабська Республіка' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_uk='Свазіленд' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_uk='Острови Теркс і Кайкос' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_uk='Чад' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_uk='Французькі Південні території' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_uk='Того' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_uk='Таїланд' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_uk='Таджикистан' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_uk='Токелау' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_uk='Туркменія' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_uk='Туніс' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_uk='Тонга' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_uk='Східний Тимор' WHERE cn_iso_2='TP';
UPDATE static_countries SET cn_short_uk='Турція' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_uk='Тринідад і Тобаго' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_uk='Тувалу' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_uk='Тайвань (Китай)' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_uk='Танзанія, об\'єднана республіка' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_uk='Україна' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_uk='Уганда' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_uk='Малі Тихоокеанські Віддалені острови США' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_uk='Сполучені Штати' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_uk='Уругвай' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_uk='Узбекістан' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_uk='Ватікан' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_uk='Сент-Вінсент и Гренадини' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_uk='Венесуела' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_uk='Віргінські острови, Британські' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_uk='Віргінські острови, США' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_uk='В\'єтнам' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_uk='Вануату' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_uk='Уолліс і Футуна' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_uk='Самоа' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_uk='Йемен' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_uk='Майотта' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_uk='Югославія' WHERE cn_iso_2='YU';
UPDATE static_countries SET cn_short_uk='Південна Африка' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_uk='Замбія' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_uk='Зімбабве' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_uk='Аландськіє острови' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_uk='Тімор-Лесте' WHERE cn_iso_2='TL';


## static_currencies
UPDATE static_currencies SET cu_name_uk='Дирхам (ОАЭ)',cu_sub_name_uk='' WHERE cu_iso_3='AED';
UPDATE static_currencies SET cu_name_uk='Лек',cu_sub_name_uk='' WHERE cu_iso_3='ALL';
UPDATE static_currencies SET cu_name_uk='Вірменський драм',cu_sub_name_uk='' WHERE cu_iso_3='AMD';
UPDATE static_currencies SET cu_name_uk='Нідерландський антільський гульден',cu_sub_name_uk='' WHERE cu_iso_3='ANG';
UPDATE static_currencies SET cu_name_uk='Кванза',cu_sub_name_uk='' WHERE cu_iso_3='AOA';
UPDATE static_currencies SET cu_name_uk='Аргентинске песо',cu_sub_name_uk='' WHERE cu_iso_3='ARS';
UPDATE static_currencies SET cu_name_uk='Австралійський долар',cu_sub_name_uk='' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_uk='Арубанській гульден',cu_sub_name_uk='' WHERE cu_iso_3='AWG';
UPDATE static_currencies SET cu_name_uk='Азербайджанський манат',cu_sub_name_uk='' WHERE cu_iso_3='AZN';
UPDATE static_currencies SET cu_name_uk='Боснійська марка',cu_sub_name_uk='' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_uk='Барбадосский долар',cu_sub_name_uk='' WHERE cu_iso_3='BBD';
UPDATE static_currencies SET cu_name_uk='Така',cu_sub_name_uk='' WHERE cu_iso_3='BDT';
UPDATE static_currencies SET cu_name_uk='Болгарский лев',cu_sub_name_uk='' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_uk='Бахрейнській динар',cu_sub_name_uk='' WHERE cu_iso_3='BHD';
UPDATE static_currencies SET cu_name_uk='Бурундійській франк',cu_sub_name_uk='' WHERE cu_iso_3='BIF';
UPDATE static_currencies SET cu_name_uk='Бермудський долар',cu_sub_name_uk='' WHERE cu_iso_3='BMD';
UPDATE static_currencies SET cu_name_uk='Брунейский долар',cu_sub_name_uk='' WHERE cu_iso_3='BND';
UPDATE static_currencies SET cu_name_uk='Боливиано',cu_sub_name_uk='' WHERE cu_iso_3='BOB';
UPDATE static_currencies SET cu_name_uk='Бразильський реал',cu_sub_name_uk='' WHERE cu_iso_3='BRL';
UPDATE static_currencies SET cu_name_uk='Багамський долар',cu_sub_name_uk='' WHERE cu_iso_3='BSD';
UPDATE static_currencies SET cu_name_uk='Нгултрум',cu_sub_name_uk='' WHERE cu_iso_3='BTN';
UPDATE static_currencies SET cu_name_uk='Пула',cu_sub_name_uk='' WHERE cu_iso_3='BWP';
UPDATE static_currencies SET cu_name_uk='Білоруський рубель',cu_sub_name_uk='' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_uk='Белізській долар',cu_sub_name_uk='' WHERE cu_iso_3='BZD';
UPDATE static_currencies SET cu_name_uk='Канадський долар',cu_sub_name_uk='' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_uk='Конголезький франк',cu_sub_name_uk='' WHERE cu_iso_3='CDF';
UPDATE static_currencies SET cu_name_uk='Швейцарський франк',cu_sub_name_uk='' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_uk='Чилійське песо',cu_sub_name_uk='' WHERE cu_iso_3='CLP';
UPDATE static_currencies SET cu_name_uk='Юань Ренминби',cu_sub_name_uk='' WHERE cu_iso_3='CNY';
UPDATE static_currencies SET cu_name_uk='Колумбійське песо',cu_sub_name_uk='' WHERE cu_iso_3='COP';
UPDATE static_currencies SET cu_name_uk='Костаріканський колон',cu_sub_name_uk='' WHERE cu_iso_3='CRC';
UPDATE static_currencies SET cu_name_uk='Кубинське песо',cu_sub_name_uk='' WHERE cu_iso_3='CUP';
UPDATE static_currencies SET cu_name_uk='Ескудо Кабо-верде',cu_sub_name_uk='' WHERE cu_iso_3='CVE';
UPDATE static_currencies SET cu_name_uk='Кіпрский фунт',cu_sub_name_uk='' WHERE cu_iso_3='CYP';
UPDATE static_currencies SET cu_name_uk='Чеська крона',cu_sub_name_uk='' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_uk='Франк Джібуті',cu_sub_name_uk='' WHERE cu_iso_3='DJF';
UPDATE static_currencies SET cu_name_uk='Данська крона',cu_sub_name_uk='' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_uk='Домініканське песо',cu_sub_name_uk='' WHERE cu_iso_3='DOP';
UPDATE static_currencies SET cu_name_uk='Алжірський динар',cu_sub_name_uk='' WHERE cu_iso_3='DZD';
UPDATE static_currencies SET cu_name_uk='Естонська крона',cu_sub_name_uk='' WHERE cu_iso_3='EEK';
UPDATE static_currencies SET cu_name_uk='Єгипетський фунт',cu_sub_name_uk='' WHERE cu_iso_3='EGP';
UPDATE static_currencies SET cu_name_uk='Накфа',cu_sub_name_uk='' WHERE cu_iso_3='ERN';
UPDATE static_currencies SET cu_name_uk='Ефіопський бир',cu_sub_name_uk='' WHERE cu_iso_3='ETB';
UPDATE static_currencies SET cu_name_uk='Євро',cu_sub_name_uk='' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_uk='Долар Фіджі',cu_sub_name_uk='' WHERE cu_iso_3='FJD';
UPDATE static_currencies SET cu_name_uk='Фунт Фолклендських островів',cu_sub_name_uk='' WHERE cu_iso_3='FKP';
UPDATE static_currencies SET cu_name_uk='Фунт стерлінгів',cu_sub_name_uk='' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_uk='Ларі',cu_sub_name_uk='' WHERE cu_iso_3='GEL';
UPDATE static_currencies SET cu_name_uk='Седи',cu_sub_name_uk='' WHERE cu_iso_3='GHC';
UPDATE static_currencies SET cu_name_uk='Гібралтарський фунт',cu_sub_name_uk='' WHERE cu_iso_3='GIP';
UPDATE static_currencies SET cu_name_uk='Даласі',cu_sub_name_uk='' WHERE cu_iso_3='GMD';
UPDATE static_currencies SET cu_name_uk='Гвінейський франк',cu_sub_name_uk='' WHERE cu_iso_3='GNF';
UPDATE static_currencies SET cu_name_uk='Кетсаль',cu_sub_name_uk='' WHERE cu_iso_3='GTQ';
UPDATE static_currencies SET cu_name_uk='Песо Гвінеї-Бісау',cu_sub_name_uk='' WHERE cu_iso_3='GWP';
UPDATE static_currencies SET cu_name_uk='Гайанській долар',cu_sub_name_uk='' WHERE cu_iso_3='GYD';
UPDATE static_currencies SET cu_name_uk='Гонконгский долдар',cu_sub_name_uk='' WHERE cu_iso_3='HKD';
UPDATE static_currencies SET cu_name_uk='Лемпира',cu_sub_name_uk='' WHERE cu_iso_3='HNL';
UPDATE static_currencies SET cu_name_uk='Куна',cu_sub_name_uk='' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_uk='Гурд',cu_sub_name_uk='' WHERE cu_iso_3='HTG';
UPDATE static_currencies SET cu_name_uk='Форинт',cu_sub_name_uk='' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_uk='Рупия',cu_sub_name_uk='' WHERE cu_iso_3='IDR';
UPDATE static_currencies SET cu_name_uk='Новий ізраїльський шекель',cu_sub_name_uk='' WHERE cu_iso_3='ILS';
UPDATE static_currencies SET cu_name_uk='Індійська рупія',cu_sub_name_uk='' WHERE cu_iso_3='INR';
UPDATE static_currencies SET cu_name_uk='Іракский дінар',cu_sub_name_uk='' WHERE cu_iso_3='IQD';
UPDATE static_currencies SET cu_name_uk='Іранский ріал',cu_sub_name_uk='' WHERE cu_iso_3='IRR';
UPDATE static_currencies SET cu_name_uk='Ісландська крона',cu_sub_name_uk='' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_uk='Ямайський долар',cu_sub_name_uk='' WHERE cu_iso_3='JMD';
UPDATE static_currencies SET cu_name_uk='Йорданський динар',cu_sub_name_uk='' WHERE cu_iso_3='JOD';
UPDATE static_currencies SET cu_name_uk='Йена',cu_sub_name_uk='' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_uk='Кенійський шилінг',cu_sub_name_uk='' WHERE cu_iso_3='KES';
UPDATE static_currencies SET cu_name_uk='Сом',cu_sub_name_uk='' WHERE cu_iso_3='KGS';
UPDATE static_currencies SET cu_name_uk='Риель',cu_sub_name_uk='' WHERE cu_iso_3='KHR';
UPDATE static_currencies SET cu_name_uk='Франк Коморськіх островів',cu_sub_name_uk='' WHERE cu_iso_3='KMF';
UPDATE static_currencies SET cu_name_uk='Північно-корейська вона',cu_sub_name_uk='' WHERE cu_iso_3='KPW';
UPDATE static_currencies SET cu_name_uk='Вона',cu_sub_name_uk='' WHERE cu_iso_3='KRW';
UPDATE static_currencies SET cu_name_uk='Кувейтський динар',cu_sub_name_uk='' WHERE cu_iso_3='KWD';
UPDATE static_currencies SET cu_name_uk='Долар Кайманових островів',cu_sub_name_uk='' WHERE cu_iso_3='KYD';
UPDATE static_currencies SET cu_name_uk='Тенге',cu_sub_name_uk='' WHERE cu_iso_3='KZT';
UPDATE static_currencies SET cu_name_uk='Кіп',cu_sub_name_uk='' WHERE cu_iso_3='LAK';
UPDATE static_currencies SET cu_name_uk='Ліванский фунт',cu_sub_name_uk='' WHERE cu_iso_3='LBP';
UPDATE static_currencies SET cu_name_uk='Шрі-Ланкійський рупій',cu_sub_name_uk='' WHERE cu_iso_3='LKR';
UPDATE static_currencies SET cu_name_uk='Ліберійський долар',cu_sub_name_uk='' WHERE cu_iso_3='LRD';
UPDATE static_currencies SET cu_name_uk='Лоти',cu_sub_name_uk='' WHERE cu_iso_3='LSL';
UPDATE static_currencies SET cu_name_uk='Литовский літ',cu_sub_name_uk='' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_uk='Латвійські лати',cu_sub_name_uk='' WHERE cu_iso_3='LVL';
UPDATE static_currencies SET cu_name_uk='Лівійський динар',cu_sub_name_uk='' WHERE cu_iso_3='LYD';
UPDATE static_currencies SET cu_name_uk='Марокканский дирхам',cu_sub_name_uk='' WHERE cu_iso_3='MAD';
UPDATE static_currencies SET cu_name_uk='Молдавский лей',cu_sub_name_uk='' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_uk='Дінар',cu_sub_name_uk='' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_uk='Кьят',cu_sub_name_uk='' WHERE cu_iso_3='MMK';
UPDATE static_currencies SET cu_name_uk='Тугрик',cu_sub_name_uk='' WHERE cu_iso_3='MNT';
UPDATE static_currencies SET cu_name_uk='Патака',cu_sub_name_uk='' WHERE cu_iso_3='MOP';
UPDATE static_currencies SET cu_name_uk='Угия',cu_sub_name_uk='' WHERE cu_iso_3='MRO';
UPDATE static_currencies SET cu_name_uk='Мальтійська ліра',cu_sub_name_uk='' WHERE cu_iso_3='MTL';
UPDATE static_currencies SET cu_name_uk='Маврікийськая рупія',cu_sub_name_uk='' WHERE cu_iso_3='MUR';
UPDATE static_currencies SET cu_name_uk='Руфія',cu_sub_name_uk='' WHERE cu_iso_3='MVR';
UPDATE static_currencies SET cu_name_uk='Квача',cu_sub_name_uk='' WHERE cu_iso_3='MWK';
UPDATE static_currencies SET cu_name_uk='Мексиканське песо',cu_sub_name_uk='' WHERE cu_iso_3='MXN';
UPDATE static_currencies SET cu_name_uk='Малайзійський рингтит',cu_sub_name_uk='' WHERE cu_iso_3='MYR';
UPDATE static_currencies SET cu_name_uk='Метікал',cu_sub_name_uk='' WHERE cu_iso_3='MZM';
UPDATE static_currencies SET cu_name_uk='Долар Намібії',cu_sub_name_uk='' WHERE cu_iso_3='NAD';
UPDATE static_currencies SET cu_name_uk='Найра',cu_sub_name_uk='' WHERE cu_iso_3='NGN';
UPDATE static_currencies SET cu_name_uk='Золота кордоба',cu_sub_name_uk='' WHERE cu_iso_3='NIO';
UPDATE static_currencies SET cu_name_uk='Норвезька крона',cu_sub_name_uk='' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_uk='Непальський рупій',cu_sub_name_uk='' WHERE cu_iso_3='NPR';
UPDATE static_currencies SET cu_name_uk='Новозеландський долар',cu_sub_name_uk='' WHERE cu_iso_3='NZD';
UPDATE static_currencies SET cu_name_uk='Оманский ріал',cu_sub_name_uk='' WHERE cu_iso_3='OMR';
UPDATE static_currencies SET cu_name_uk='Бальбоа',cu_sub_name_uk='' WHERE cu_iso_3='PAB';
UPDATE static_currencies SET cu_name_uk='Новий соль',cu_sub_name_uk='' WHERE cu_iso_3='PEN';
UPDATE static_currencies SET cu_name_uk='Кина',cu_sub_name_uk='' WHERE cu_iso_3='PGK';
UPDATE static_currencies SET cu_name_uk='Філіппінське песо',cu_sub_name_uk='' WHERE cu_iso_3='PHP';
UPDATE static_currencies SET cu_name_uk='Пакистанський рупій',cu_sub_name_uk='' WHERE cu_iso_3='PKR';
UPDATE static_currencies SET cu_name_uk='Злотий',cu_sub_name_uk='' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_uk='Гуарани',cu_sub_name_uk='' WHERE cu_iso_3='PYG';
UPDATE static_currencies SET cu_name_uk='Катарский ріал',cu_sub_name_uk='' WHERE cu_iso_3='QAR';
UPDATE static_currencies SET cu_name_uk='Лей',cu_sub_name_uk='' WHERE cu_iso_3='ROL';
UPDATE static_currencies SET cu_name_uk='Російський рубель',cu_sub_name_uk='' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_uk='Франк Руанди',cu_sub_name_uk='' WHERE cu_iso_3='RWF';
UPDATE static_currencies SET cu_name_uk='Саудівський риял',cu_sub_name_uk='' WHERE cu_iso_3='SAR';
UPDATE static_currencies SET cu_name_uk='Долар Соломонових островів',cu_sub_name_uk='' WHERE cu_iso_3='SBD';
UPDATE static_currencies SET cu_name_uk='Сейшельський рупій',cu_sub_name_uk='' WHERE cu_iso_3='SCR';
UPDATE static_currencies SET cu_name_uk='Суданский динар',cu_sub_name_uk='' WHERE cu_iso_3='SDD';
UPDATE static_currencies SET cu_name_uk='Шведська крона',cu_sub_name_uk='' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_uk='Сінгапурський долар',cu_sub_name_uk='' WHERE cu_iso_3='SGD';
UPDATE static_currencies SET cu_name_uk='Фунт Острова Святої Олени',cu_sub_name_uk='' WHERE cu_iso_3='SHP';
UPDATE static_currencies SET cu_name_uk='Толар',cu_sub_name_uk='' WHERE cu_iso_3='SIT';
UPDATE static_currencies SET cu_name_uk='Словацька крона',cu_sub_name_uk='' WHERE cu_iso_3='SKK';
UPDATE static_currencies SET cu_name_uk='Леоні',cu_sub_name_uk='' WHERE cu_iso_3='SLL';
UPDATE static_currencies SET cu_name_uk='Шилінг, Сомалі',cu_sub_name_uk='' WHERE cu_iso_3='SOS';
UPDATE static_currencies SET cu_name_uk='Добра',cu_sub_name_uk='' WHERE cu_iso_3='STD';
UPDATE static_currencies SET cu_name_uk='Сальвадорський колон',cu_sub_name_uk='' WHERE cu_iso_3='SVC';
UPDATE static_currencies SET cu_name_uk='Сірійський фунт',cu_sub_name_uk='' WHERE cu_iso_3='SYP';
UPDATE static_currencies SET cu_name_uk='Лілангені',cu_sub_name_uk='' WHERE cu_iso_3='SZL';
UPDATE static_currencies SET cu_name_uk='Бат',cu_sub_name_uk='' WHERE cu_iso_3='THB';
UPDATE static_currencies SET cu_name_uk='Сомоні',cu_sub_name_uk='' WHERE cu_iso_3='TJS';
UPDATE static_currencies SET cu_name_uk='Манат',cu_sub_name_uk='' WHERE cu_iso_3='TMM';
UPDATE static_currencies SET cu_name_uk='Туніський динар',cu_sub_name_uk='' WHERE cu_iso_3='TND';
UPDATE static_currencies SET cu_name_uk='Паанга',cu_sub_name_uk='' WHERE cu_iso_3='TOP';
UPDATE static_currencies SET cu_name_uk='Долар Тринідаду і Тобаго',cu_sub_name_uk='' WHERE cu_iso_3='TTD';
UPDATE static_currencies SET cu_name_uk='Новий тайваньський долар',cu_sub_name_uk='' WHERE cu_iso_3='TWD';
UPDATE static_currencies SET cu_name_uk='Танзанийский шилінг',cu_sub_name_uk='' WHERE cu_iso_3='TZS';
UPDATE static_currencies SET cu_name_uk='Гривня',cu_sub_name_uk='' WHERE cu_iso_3='ukH';
UPDATE static_currencies SET cu_name_uk='Угандийский шилінг',cu_sub_name_uk='' WHERE cu_iso_3='UGX';
UPDATE static_currencies SET cu_name_uk='Долар США',cu_sub_name_uk='' WHERE cu_iso_3='USD';
UPDATE static_currencies SET cu_name_uk='Уругвайське песо',cu_sub_name_uk='' WHERE cu_iso_3='UYU';
UPDATE static_currencies SET cu_name_uk='Узбецький сум',cu_sub_name_uk='' WHERE cu_iso_3='UZS';
UPDATE static_currencies SET cu_name_uk='Болівар',cu_sub_name_uk='' WHERE cu_iso_3='VEB';
UPDATE static_currencies SET cu_name_uk='Донг',cu_sub_name_uk='' WHERE cu_iso_3='VND';
UPDATE static_currencies SET cu_name_uk='Вату',cu_sub_name_uk='' WHERE cu_iso_3='VUV';
UPDATE static_currencies SET cu_name_uk='Тала',cu_sub_name_uk='' WHERE cu_iso_3='WST';
UPDATE static_currencies SET cu_name_uk='Франк КФА ВЕАС',cu_sub_name_uk='' WHERE cu_iso_3='XAF';
UPDATE static_currencies SET cu_name_uk='Східно-карибський долар',cu_sub_name_uk='' WHERE cu_iso_3='XCD';
UPDATE static_currencies SET cu_name_uk='Франк КФА ВСЕАО',cu_sub_name_uk='' WHERE cu_iso_3='XOF';
UPDATE static_currencies SET cu_name_uk='Франк КФП',cu_sub_name_uk='' WHERE cu_iso_3='XPF';
UPDATE static_currencies SET cu_name_uk='Йеменський ріал',cu_sub_name_uk='' WHERE cu_iso_3='YER';
UPDATE static_currencies SET cu_name_uk='Ренд',cu_sub_name_uk='' WHERE cu_iso_3='ZAR';
UPDATE static_currencies SET cu_name_uk='Квача (замбийская)',cu_sub_name_uk='' WHERE cu_iso_3='ZMK';
UPDATE static_currencies SET cu_name_uk='Долар Зімбабве',cu_sub_name_uk='' WHERE cu_iso_3='ZWD';
UPDATE static_currencies SET cu_name_uk='Афгани',cu_sub_name_uk='' WHERE cu_iso_3='AFN';
UPDATE static_currencies SET cu_name_uk='Сербский динар',cu_sub_name_uk='' WHERE cu_iso_3='CSD';
UPDATE static_currencies SET cu_name_uk='Франк, Малаги',cu_sub_name_uk='' WHERE cu_iso_3='MGA';
UPDATE static_currencies SET cu_name_uk='Суринамский долар',cu_sub_name_uk='' WHERE cu_iso_3='SRD';
UPDATE static_currencies SET cu_name_uk='Турецка ліра',cu_sub_name_uk='' WHERE cu_iso_3='TRY';


## static_languages
UPDATE static_languages SET lg_name_uk='Абхазька' WHERE lg_iso_2='AB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Афар' WHERE lg_iso_2='AA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Африкаанс' WHERE lg_iso_2='AF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Албанська' WHERE lg_iso_2='SQ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Амхарська' WHERE lg_iso_2='AM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Арабська' WHERE lg_iso_2='AR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Вірменська' WHERE lg_iso_2='HY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Асамська' WHERE lg_iso_2='AS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Аймара' WHERE lg_iso_2='AY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Азербайджанська' WHERE lg_iso_2='AZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Башкірська' WHERE lg_iso_2='BA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Баська' WHERE lg_iso_2='EU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Бенгальська' WHERE lg_iso_2='BN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Дзонг-ке' WHERE lg_iso_2='DZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Біхарська' WHERE lg_iso_2='BH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Бісламська' WHERE lg_iso_2='BI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Бретонська' WHERE lg_iso_2='BR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Болгарська' WHERE lg_iso_2='BG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Бырманська' WHERE lg_iso_2='MY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Білоруська' WHERE lg_iso_2='BE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Кхмерська' WHERE lg_iso_2='KM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Каталонська' WHERE lg_iso_2='CA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Чжуаньська' WHERE lg_iso_2='ZA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Китайська' WHERE lg_iso_2='ZH' AND lg_country_iso_2='HK';
UPDATE static_languages SET lg_name_uk='Корсіканська' WHERE lg_iso_2='CO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Хорватська' WHERE lg_iso_2='HR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Чеська' WHERE lg_iso_2='CS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Данська' WHERE lg_iso_2='DA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Нідерландська' WHERE lg_iso_2='NL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Англійська' WHERE lg_iso_2='EN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Есперанто' WHERE lg_iso_2='EO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Естонська' WHERE lg_iso_2='ET' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Фарерська' WHERE lg_iso_2='FO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Персидська' WHERE lg_iso_2='FA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Фіджі' WHERE lg_iso_2='FJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Фінська' WHERE lg_iso_2='FI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Французька' WHERE lg_iso_2='FR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Фризька' WHERE lg_iso_2='FY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Галісийська' WHERE lg_iso_2='GL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Шотландська' WHERE lg_iso_2='GD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Менська' WHERE lg_iso_2='GV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Грузинська' WHERE lg_iso_2='KA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Німецька' WHERE lg_iso_2='DE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Грецька' WHERE lg_iso_2='EL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Калмицька' WHERE lg_iso_2='KL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Гуаранська' WHERE lg_iso_2='GN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Гуджаратійська' WHERE lg_iso_2='GU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Хауса' WHERE lg_iso_2='HA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Іврит' WHERE lg_iso_2='HE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Хінді' WHERE lg_iso_2='HI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Венгерська' WHERE lg_iso_2='HU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Ісландська' WHERE lg_iso_2='IS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Індонезійська' WHERE lg_iso_2='ID' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Інуктітут' WHERE lg_iso_2='IU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Інупіак' WHERE lg_iso_2='IK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Ірландська' WHERE lg_iso_2='GA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Італійська' WHERE lg_iso_2='IT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Японська' WHERE lg_iso_2='JA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Каннада' WHERE lg_iso_2='KN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Кашмірі' WHERE lg_iso_2='KS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Казахська' WHERE lg_iso_2='KK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Киньяруанда' WHERE lg_iso_2='RW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Киргизька' WHERE lg_iso_2='KY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Рунді' WHERE lg_iso_2='RN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Корейська' WHERE lg_iso_2='KO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Курдська' WHERE lg_iso_2='KU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Лаосский' WHERE lg_iso_2='LO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Латиська' WHERE lg_iso_2='LV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Лінгала' WHERE lg_iso_2='LN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Литовська' WHERE lg_iso_2='LT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Македонська' WHERE lg_iso_2='MK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Малага' WHERE lg_iso_2='MG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Малайська' WHERE lg_iso_2='MS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Малаялям' WHERE lg_iso_2='ML' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Мальтійська' WHERE lg_iso_2='MT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Маорі' WHERE lg_iso_2='MI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Маратхі' WHERE lg_iso_2='MR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Молдавська' WHERE lg_iso_2='MO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Монгольська' WHERE lg_iso_2='MN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Науру' WHERE lg_iso_2='NA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Непальська' WHERE lg_iso_2='NE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Норвежська' WHERE lg_iso_2='NO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Окситанська' WHERE lg_iso_2='OC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Орія' WHERE lg_iso_2='OR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Оромо' WHERE lg_iso_2='OM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Пушту' WHERE lg_iso_2='PS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Польська' WHERE lg_iso_2='PL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Португальська' WHERE lg_iso_2='PT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Панджаби' WHERE lg_iso_2='PA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Кечуа' WHERE lg_iso_2='QU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Ретороманська' WHERE lg_iso_2='RM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Румунська' WHERE lg_iso_2='RO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Російська' WHERE lg_iso_2='RU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Самоанська' WHERE lg_iso_2='SM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Санго' WHERE lg_iso_2='SG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Сербська' WHERE lg_iso_2='SR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Сото Південний' WHERE lg_iso_2='ST' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Тсвана' WHERE lg_iso_2='TN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Шона' WHERE lg_iso_2='SN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Синдхи' WHERE lg_iso_2='SD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Сингальська' WHERE lg_iso_2='SI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Свази' WHERE lg_iso_2='SS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Словацька' WHERE lg_iso_2='SK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Словенська' WHERE lg_iso_2='SL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Сомалі' WHERE lg_iso_2='SO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Іспанська' WHERE lg_iso_2='ES' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Сунданська' WHERE lg_iso_2='SU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Суахілі' WHERE lg_iso_2='SW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Шведська' WHERE lg_iso_2='SV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Тагальська' WHERE lg_iso_2='TL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Таджицька' WHERE lg_iso_2='TG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Тамільська' WHERE lg_iso_2='TA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Татарська' WHERE lg_iso_2='TT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Телугу' WHERE lg_iso_2='TE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Тайська' WHERE lg_iso_2='TH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Тибет' WHERE lg_iso_2='BO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Тігрінья' WHERE lg_iso_2='TI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Тонга (Тонга Ісландська)' WHERE lg_iso_2='TO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Тсонга' WHERE lg_iso_2='TS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Турецька' WHERE lg_iso_2='TR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Туркменська' WHERE lg_iso_2='TK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Тві' WHERE lg_iso_2='TW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Уйгурська' WHERE lg_iso_2='UG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Українська' WHERE lg_iso_2='UK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Урду' WHERE lg_iso_2='UR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Узбецька' WHERE lg_iso_2='UZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='В\'єтнамська' WHERE lg_iso_2='VI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Валлійська (Уельська)' WHERE lg_iso_2='CY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Волоф' WHERE lg_iso_2='WO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Коса' WHERE lg_iso_2='XH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Йоруба' WHERE lg_iso_2='YO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Зулу' WHERE lg_iso_2='ZU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Боснійська' WHERE lg_iso_2='BS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Акан' WHERE lg_iso_2='AK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Арагонська' WHERE lg_iso_2='AN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Аварська' WHERE lg_iso_2='AV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Бамбара' WHERE lg_iso_2='BM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Чеченська' WHERE lg_iso_2='CE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Чаморро' WHERE lg_iso_2='CH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Крі' WHERE lg_iso_2='CR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Чуваська' WHERE lg_iso_2='CV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Дівехи (Мальдівська)' WHERE lg_iso_2='DV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Еве' WHERE lg_iso_2='EE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Фулах' WHERE lg_iso_2='FF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Хирімоту' WHERE lg_iso_2='HO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Гаїтянська' WHERE lg_iso_2='HT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Гереро' WHERE lg_iso_2='HZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Ігбо' WHERE lg_iso_2='IG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Сичуань' WHERE lg_iso_2='II' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Конго' WHERE lg_iso_2='KG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Кикуйю' WHERE lg_iso_2='KI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Киньяма' WHERE lg_iso_2='KJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Канурі' WHERE lg_iso_2='KR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Комі' WHERE lg_iso_2='KV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Корнська' WHERE lg_iso_2='KW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Люксембурзька' WHERE lg_iso_2='LB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Ганда' WHERE lg_iso_2='LG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Лімбургийська' WHERE lg_iso_2='LI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Луба-Катанга' WHERE lg_iso_2='LU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Маршальська' WHERE lg_iso_2='MH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Норвезька бокмол' WHERE lg_iso_2='NB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Ндебеле північна' WHERE lg_iso_2='ND' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Ндунга' WHERE lg_iso_2='NG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Нюнорська (Новонорвежська)' WHERE lg_iso_2='NN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Ндебеле південна' WHERE lg_iso_2='NR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Навахо' WHERE lg_iso_2='NV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Ньянджа' WHERE lg_iso_2='NY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Оджібва' WHERE lg_iso_2='OJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Осетинська' WHERE lg_iso_2='OS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Сардінська' WHERE lg_iso_2='SC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Північно-саамська' WHERE lg_iso_2='SE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Таітянська' WHERE lg_iso_2='TY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Венда' WHERE lg_iso_2='VE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Валлонська' WHERE lg_iso_2='WA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Яванецька' WHERE lg_iso_2='JV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Португальська' WHERE lg_iso_2='PT' AND lg_country_iso_2='BR';
UPDATE static_languages SET lg_name_uk='Китайська' WHERE lg_iso_2='ZH' AND lg_country_iso_2='CN';
UPDATE static_languages SET lg_name_uk='Інтерлінгва' WHERE lg_iso_2='IA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Інтерлінгве' WHERE lg_iso_2='IE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Латинська' WHERE lg_iso_2='LA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Санскрит' WHERE lg_iso_2='SA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Волапюк' WHERE lg_iso_2='VO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Ідиш' WHERE lg_iso_2='YI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Авестійська' WHERE lg_iso_2='AE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Церковно-слов\'янська' WHERE lg_iso_2='CU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Ідо' WHERE lg_iso_2='IO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_uk='Пали' WHERE lg_iso_2='PI' AND lg_country_iso_2='';


